@startuml secondary_server_timeline
skinparam DefaultTextAlignment CENTER
skinparam ActivityBackgroundColor #060662a8
skinparam DefaultFontColor #ffffff
skinparam ArrowColor #ffbb00
skinparam ActivityBorderColor #0000ff
:SecondaryServer;
split
:main thread;
detach
split again
:SecondaryHeartbeat;
detach
split again
:UDPAccept;
:UDPTransfer;
detach
split again
:UDPCommandReceiver;
:UDPCommandHandler;
detach

@enduml